//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sdk.Plugin.Properties
{
    /// <summary>
    /// A strongly typed resource class intended, among other things, for consulting localized strings
    /// </summary>
    // This class was automatically generated by the StronglyTypedResourceBuilder class
    // using a tool such as ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file, then run ResGen again
    // with the /str option or regenerate your VS project
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns cached ResourceManager instance used by this class
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sdk.Plugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the CurrentUICulture property of the current thread
        ///   for all resource searches using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  Searches for a localized resource of type System.Drawing.Bitmap
        /// </summary>
        internal static System.Drawing.Bitmap sdkmenuicon {
            get {
                object obj = ResourceManager.GetObject("sdkmenuicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
